= Servitude

== Les servitudes attachées au droit de propriété, une prestation foncière du géomètre-expert

Dans le cadre d’une mutation ou d’une division, le géomètre-expert analyse les servitudes existantes, celles devant être créées et celles devant être éteintes.

Pourquoi mandater un géomètre-expert pour l’examen des servitudes ?
Le donneur d’ordre est en questionnement ou en attente d’un avis d’expert sur l’existence d’une servitude et ses modalités d’exercice ? Pour éviter des situations de litiges, le géomètre-expert est mandaté pour fournir un conseil juridique. Il offre son regard expert sur les servitudes existantes ou à venir.

Passage, canalisation, réseau, vue, écoulement des eaux : une servitude
grève un fonds au profit d'un autre et doit être décrite sans ambiguïté.

Quelles sont les missions du géomètre-expert en cas de sollicitation sur un projet de servitude ?
Dans le cadre d’une sollicitation pour un projet de servitudes au droit de propriété, le géomètre-expert remplit plusieurs missions :

* examine les titres existants et publiés,
* vérifie les fonds d’origine et les servitudes non publiées,
* identifie les servitudes ou modalités d’exercice,
* dresse la désignation et les conclusions de l’analyse,
* dresse le plan récapitulatif comprenant les positions et les natures des différentes servitudes,
* transmet les documents au notaire pour être annexés à l'acte notarié.
