= Concordance cadastrale

L’établissement de l’origine d’une propriété, la recherche d’héritiers ou d’une servitude peuvent nécessiter une analyse comparée de l’ancien cadastre et du cadastre actuel.

Foncier

La concordance cadastrale, une prestation foncière du géomètre-expert
Dans les faits, la concordance cadastrale est la comparaison de l’ancien et du nouveau cadastre afin de déceler une correspondance ou non entre ces deux documents. La concordance cadastrale intervient dans l’établissement de l’origine d’une propriété, la recherche d’héritiers ou encore d’une servitude.

En quoi consiste la mission de concordance cadastrale ?
Le géomètre-expert se charge d’identifier l’évolution dans le temps de la consistance d’une parcelle et de ses propriétaires successifs.

== La mission opérationnelle de concordance cadastrale consiste à :

Identifier l’évolution dans le temps de la consistance de la parcelle et des propriétaires successifs,
Consulter les archives locales en vue de l’identification des parcelles ou des propriétaires,
Consulter les informations présentées sur le portail GEOFONCIER.fr,
Consulter les états de sections, des matrices cadastrales, des anciens plans, de l’extrait de propriété, des actes successifs, dans le cadre du suivi des mutations,
Procéder à l’analyse graphique entre l’ancien et le nouveau plan pour comparer les parcelles,
Rédiger un rapport et établir une attestation de correspondance certifiée, datée et signée.

----------------------------------------------

Conservation cadastrale et publicité foncière
Le géomètre-expert est habilité à établir les documents modificatifs du parcellaire cadastral (DMPC), une obligation dans le cadre de tout changement de limites de propriétés.

Foncier

La conservation cadastrale, une prestation du géomètre-expert
Le géomètre-expert est habilité à établir les documents modificatifs du parcellaire cadastral (DMPC), une obligation dans le cadre de tout changement de limites de propriétés, tels que :

les divisions,
les lotissements,
les partages,
ou les échanges.
Préalablement à la rédaction de l’acte réalisant le changement de limite, le géomètre-expert produit le document de mise à jour du plan cadastral, en concordance avec le fichier immobilier du service de la publicité foncière.

Le DMPC ne peut être établi qu’à la demande des propriétaires puisqu’il constate leur volonté de réaliser un nouvel agencement des parcelles cadastrales.

En quoi consiste la mission de conservation cadastrale ?
La mission consiste à procéder à l’application de nouvelles limites sur le plan cadastral. Le géomètre-expert garantit une bonne intégration géométrique de ces nouvelles limites foncières dans le plan cadastral.

En cas de discordance importante entre l’état des lieux et le plan cadastral
Si le géomètre-expert constate une discordance importante entre l’état des lieux et le plan cadastral, il informe les parties de la nécessité de procéder à des investigations complémentaires, l’objectif étant d’éviter des litiges ultérieurs.
